In [5]:
# Create 5 matrices with five different dimensions (1-D,2-D,...5-D)
import numpy as np

# 1-D Matrix
matrix_1d = np.array([1, 2, 3, 4, 5])

# 2-D Matrix
matrix_2d = np.array([[1, 2, 3],
                      [4, 5, 6]])

# 3-D Matrix
matrix_3d = np.array([[[1, 2],
                       [3, 4]],
                      
                      [[5, 6],
                       [7, 8]]])

# 4-D Matrix
matrix_4d = np.array([[[1, 2],
                        [3, 4]],
                       
                       [[5, 6],
                        [7, 8]]])

# 5-D Matrix
matrix_5d = np.array([[[[1, 2],
                         [3, 4]],
                        
                        [[5, 6],
                         [7, 8]]]])

# Printing the matrices
print("1-D Matrix:")
print(matrix_1d)

print("\n2-D Matrix:")
print(matrix_2d)

print("\n3-D Matrix:")
print(matrix_3d)

print("\n4-D Matrix:")
print(matrix_4d)

print("\n5-D Matrix:")
print(matrix_5d)

1-D Matrix:
[1 2 3 4 5]

2-D Matrix:
[[1 2 3]
 [4 5 6]]

3-D Matrix:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

4-D Matrix:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

5-D Matrix:
[[[[1 2]
   [3 4]]

  [[5 6]
   [7 8]]]]


In [6]:
# Find determinants of 5 matrices and display your output
import numpy as np

# Define 5 matrices as NumPy arrays
matrices = []

matrix1 = np.array([[1, 2],
                    [3, 4]])

matrix2 = np.array([[5, 6],
                    [7, 8]])

matrix3 = np.array([[9, 10],
                    [11, 12]])

matrix4 = np.array([[13, 14],
                    [15, 16]])

matrix5 = np.array([[17, 18],
                    [19, 20]])

matrices.extend([matrix1, matrix2, matrix3, matrix4, matrix5])

# Calculate and display the determinants of the matrices
for i, matrix in enumerate(matrices, start=1):
    determinant = np.linalg.det(matrix)
    print(f"Determinant of matrix {i}:\n{determinant}\n")



Determinant of matrix 1:
-2.0000000000000004

Determinant of matrix 2:
-2.000000000000005

Determinant of matrix 3:
-1.9999999999999984

Determinant of matrix 4:
-1.9999999999999931

Determinant of matrix 5:
-2.000000000000056



In [7]:
# Find inverse of the above 5 matrices and display your output
import numpy as np

# Define 5 matrices as NumPy arrays
matrices = []

matrix1 = np.array([[1, 2],
                    [3, 4]])

matrix2 = np.array([[5, 6],
                    [7, 8]])

matrix3 = np.array([[9, 10],
                    [11, 12]])

matrix4 = np.array([[13, 14],
                    [15, 16]])

matrix5 = np.array([[17, 18],
                    [19, 20]])

matrices.extend([matrix1, matrix2, matrix3, matrix4, matrix5])

# Calculate and display the inverses of the matrices
for i, matrix in enumerate(matrices, start=1):
    try:
        inverse_matrix = np.linalg.inv(matrix)
        print(f"Inverse of matrix {i}:\n{inverse_matrix}\n")
    except np.linalg.LinAlgError:
        print(f"Matrix {i} is singular and does not have an inverse.\n")




Inverse of matrix 1:
[[-2.   1. ]
 [ 1.5 -0.5]]

Inverse of matrix 2:
[[-4.   3. ]
 [ 3.5 -2.5]]

Inverse of matrix 3:
[[-6.   5. ]
 [ 5.5 -4.5]]

Inverse of matrix 4:
[[-8.   7. ]
 [ 7.5 -6.5]]

Inverse of matrix 5:
[[-10.    9. ]
 [  9.5  -8.5]]



In [8]:
# Find the rank, diagonal and trace of the 5 matrices
import numpy as np

# Define 5 matrices as NumPy arrays
matrices = []

matrix1 = np.array([[1, 2],
                    [3, 4]])

matrix2 = np.array([[5, 6],
                    [7, 8]])

matrix3 = np.array([[9, 10],
                    [11, 12]])

matrix4 = np.array([[13, 14],
                    [15, 16]])

matrix5 = np.array([[17, 18],
                    [19, 20]])

matrices.extend([matrix1, matrix2, matrix3, matrix4, matrix5])

# Calculate and display the rank, diagonal, and trace of the matrices
for i, matrix in enumerate(matrices, start=1):
    # Rank
    rank = np.linalg.matrix_rank(matrix)
    
    # Diagonal elements
    diagonal = np.diag(matrix)
    
    # Trace
    trace = np.trace(matrix)
    
    print(f"Matrix {i}:\n")
    print(f"Rank: {rank}\n")
    print(f"Diagonal: {diagonal}\n")
    print(f"Trace: {trace}\n")



Matrix 1:

Rank: 2

Diagonal: [1 4]

Trace: 5

Matrix 2:

Rank: 2

Diagonal: [5 8]

Trace: 13

Matrix 3:

Rank: 2

Diagonal: [ 9 12]

Trace: 21

Matrix 4:

Rank: 2

Diagonal: [13 16]

Trace: 29

Matrix 5:

Rank: 2

Diagonal: [17 20]

Trace: 37



In [9]:
# Find Eigen value and eigen vector for 5 matrices
import numpy as np

# Define 5 matrices as NumPy arrays
matrices = []

matrix1 = np.array([[1, 2],
                    [3, 4]])

matrix2 = np.array([[5, 6],
                    [7, 8]])

matrix3 = np.array([[9, 10],
                    [11, 12]])

matrix4 = np.array([[13, 14],
                    [15, 16]])

matrix5 = np.array([[17, 18],
                    [19, 20]])

matrices.extend([matrix1, matrix2, matrix3, matrix4, matrix5])

# Calculate and display the eigenvalues and eigenvectors of the matrices
for i, matrix in enumerate(matrices, start=1):
    eigenvalues, eigenvectors = np.linalg.eig(matrix)
    
    print(f"Matrix {i}:\n")
    print(f"Eigenvalues:\n{eigenvalues}\n")
    print(f"Eigenvectors:\n{eigenvectors}\n")



Matrix 1:

Eigenvalues:
[-0.37228132  5.37228132]

Eigenvectors:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]

Matrix 2:

Eigenvalues:
[-0.15206735 13.15206735]

Eigenvectors:
[[-0.75868086 -0.59276441]
 [ 0.65146248 -0.80537591]]

Matrix 3:

Eigenvalues:
[-0.09481005 21.09481005]

Eigenvectors:
[[-0.73979641 -0.63720844]
 [ 0.67283079 -0.77069151]]

Matrix 4:

Eigenvalues:
[-0.06880228 29.06880228]

Eigenvectors:
[[-0.73099964 -0.65690325]
 [ 0.68237784 -0.75397488]]

Matrix 5:

Eigenvalues:
[-0.05397532 37.05397532]

Eigenvectors:
[[-0.72592563 -0.66796817]
 [ 0.68777321 -0.74418984]]

